server:
  port: 8762

spring:
  application:
    name: server-starter

  profiles:
    active: dev

  jpa:
    open-in-view: false

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8761

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}